name: release-please
on:
  push:
    branches:
      - main
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true
      - run: echo 43
      - name: Dump GitHub context
        env:
          RELEASE_OUTPUTS: ${{ toJson(steps.release.outputs) }}
        run: echo "$RELEASE_OUTPUTS"
      - run: echo ${{ steps.release.outputs.release_created }}
      - run: echo ${{ steps.release.outputs.releases_created }}

      # === NPM Publishing ===
      - uses: actions/checkout@v2
        # Only run when a new release is created
        if: ${{ steps.release.outputs.releases_created }}
      - uses: pnpm/action-setup@v2
        if: ${{ steps.release.outputs.releases_created }}
      - uses: actions/setup-node@v2
        if: ${{ steps.release.outputs.releases_created }}
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
          cache: "pnpm"
      - run: pnpm install
        if: ${{ steps.release.outputs.releases_created }}
      - run: pnpm run build
        if: ${{ steps.release.outputs.releases_created }}
      - run: npm publish
        if: ${{ steps.release.outputs.releases_created }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
